### ISSUE TITLE
Curse of Binding

### ISSUE THREAD

**Issue by BoyWonderFTW** [Seamonster778778778788/SQBeyondPublic#286]
I bought unfortunately Fortunate, the pic from the forge, and it has the curse. I can take it off and its in my chest right now. Is that right

**Comment by Seamonster778778778788** [comment]
Binding is meant to only work on armor. No idea why it's set like that.

**Comment by GingerWalnut** [comment]
I didn't know that the curse of binding only works on armor when I made the forge tools.

**Comment by Seamonster778778778788** [comment]
So basically just remove curse of binding on none-armor forge stuff
