### ISSUE TITLE
Carriers Deleting ships

### ISSUE THREAD

**Issue by Yargon-Kerman** [Seamonster778778778788/SQBeyondPublic#332]
Carrier ships (in this case a Capital ship) seem to have a habit of deleting pieces of or whole ships stored internally.

**Comment by GingerWalnut** [comment]
Is there anything in particular that might cause it to happen? Is there any chance that you flew through a nano mine field?

**Comment by Yargon-Kerman** [comment]
Nope, it was literally an autopilot jump away and then back to the parking place for the carrier

**Comment by Yargon-Kerman** [comment]
Also, we noticed it deleting the glass on a previous jump. Probably because of how it removes glass when you fly through it.
