### ISSUE TITLE
Strange Docking Tube Issue

### ISSUE THREAD

**Issue by Tongonto** [Seamonster778778778788/SQBeyondPublic#383]
On my ship I have a Radar III module, so I've got that big 3x3x3 block of glass up there. Directly underneath it is the door to my ship, which doubles as a docking tube. I docked at Skydogs station with the docking tube, and when I retracted my docking tube, well, this happened: ![image](https://cdn.discordapp.com/attachments/253006442288775168/599608844255100943/2019-07-13_10.27.20.png)

When I try to activate the docking tube again, I get a message saying the docking tube is obstructed by a ladder. While the actual docking tube (now intact, normally retracted) is unobstructed, there are some ladders in front of my now button-covered Radar III, so it seems like it's trying to use those 6 buttons on the former radar as the docking tube.

**Comment by icekoob** [comment]
i had this on my friend's plain glass cockpit

**Comment by Seamonster778778778788** [comment]
Happened to Rocky a few days ago
