### ISSUE TITLE
Right clicking internally

### ISSUE THREAD

**Issue by Jarkyc** [Seamonster778778778788/SQBeyondPublic#407]
One of the plugins is firing an event as if you are right-clicking, even though you aren't. Only is firing internally though. Like, it will active MCMMO and blasters, but if you hold a block, it isn't placing it. Garuda has had the same problem. I haven't found out how it happens yet, never really pay attention until my screen is spammed with "you ready your fists".

**Comment by Seamonster778778778788** [comment]
related to #411 ? @Jarkyc

**Comment by Jarkyc** [comment]
> related to #411 ? @Jarkyc

Sort of. It does do this if the glitch happens and you have machines running, but I’m not sure if it’s SQTechs fault.
