### ISSUE TITLE
SQTech clicks for player

### ISSUE THREAD

**Issue by Laserlance141** [Seamonster778778778788/SQBeyondPublic#411]
Title, noticed with moving machines while holding a pickaxe, mainly it was attempting to activate mcmmo repair and other mcmmo abilitys

**Comment by Seamonster778778778788** [comment]
explain more? @Laserlance141

**Comment by Laserlance141** [comment]
When I run a SQTech drill, my screen gets spamed by mcmmo messages, along with one that says something about not having perms to break a block (It still breaks and everything, so I have no idea why it says it). It also seems to count the broken blocks to mcmmo xp, and also applys mcmmo perks to whatever gets mined by the drill, along with using my current tool perks for these extra drops. These drops do not end up in the Machine Storage (The droppers behind the Piston) but instead are dropped on the ground. I assume this is because of some update that changed the way that SQTech handles the perms of breaking blocks. I'll post some screenshots of the spam when I get home.

**Comment by Laserlance141** [comment]
![image](https://user-images.githubusercontent.com/13091148/64483487-287cd200-d1b7-11e9-9606-ac6763060dc8.png)
