### ISSUE TITLE
Paid twice for quests

### ISSUE THREAD

**Issue by LispIsChad** [Seamonster778778778788/SQBeyondPublic#460]
I bought a fighter at spawn in order to do the 'leave spawn' quest, but I was informed by someone that I needed to click on the [step-by-step guide] button in the book first and had to buy another one. (IDK if this is correct)
I bought a fighter, followed the instructions the quest gave me, and when I completed it the 'quest completed' message appeared twice and I appeared to have gotten 20K instead of the 10K  that was the normal quest reward.
![Screenshot 2020-01-03 at 21 46 06](https://user-images.githubusercontent.com/59516949/71772318-c1dfa900-2f49-11ea-96eb-8c66d4b6814f.png)
Later I did the cryopod quest, this time by clicking on the step-by-step guide button before doing anything, and when I broke and re-made my cryopod the 'quest completed' message appeared again and I was (I think) also paid again. (Forgot to screenshot this time)

**Comment by Seamonster778778778788** [comment]
#467 #468 #465 #338 More quest issues
