### ISSUE TITLE
Join a town quest not working

### ISSUE THREAD

**Issue by BlueCrystal-78** [Seamonster778778778788/SQBeyondPublic#468]
![Untitled](https://user-images.githubusercontent.com/59983671/72573222-253ed480-3882-11ea-84a8-5f46f49e6eaa.png)
I'm not sure what is causing this, but it might be because the daily contract quest is active
I don't know if it's active or not because I have no way of checking, or deactivating it

**Comment by Seamonster778778778788** [comment]
@BlueCrystal-78 is this still occurring?

**Comment by BlueCrystal-78** [comment]
I haven’t logged on in a while, let me check…

…

yes
