### ISSUE TITLE
./plot commands NOT WORKING properly

### ISSUE THREAD

**Issue by Johny2268** [Seamonster778778778788/SQBeyondPublic#471]
**Hello dev team! Please fix this asap.**

As I put plot for sale (for my residents/me) by command **/plot fs** or **/plot forsale**, it put the plot for sale as it is supposed to, but when I or any resident then try to claim the plot (with **/plot claim**), it will just say "**Proccessing Plot Claim...**" and won't really claim anything. It doesn't matter if I put the plot for sale for some money or for nothing. This is really neede so each citizen would have permissions on his/her plot and not on plots of other citizens. So once more, **please fix this.**

**Comment by MrBarramundi** [comment]
Please fix this a soon as possible. I need this for my peace plans. Thank you, Mr. B.

**Comment by MrBarramundi** [comment]
Can we give this the High Priority label? This command is a pretty big part of towny & how you create towns.

**Comment by Pairjax** [comment]
This has top priority. We will let you know as soon as it is fixed.
