### ISSUE TITLE
charger

### ISSUE THREAD

**Issue by paddytheangrySRMOD** [Seamonster778778778788/SQBeyondPublic#509]
Bug: chargers
What happend?: when shift clicking items in the charger items placed in are then lost i am assumeing due to time of the shift clicking however it has caused lost of items

**Comment by Seamonster778778778788** [comment]
chargers also cause lag

**Comment by Griffinwizard** [comment]
Fixed

**Comment by fin444** [comment]
Appears to be happening again, charger just ate my pickaxe
