### ISSUE TITLE
invrestore doesn't work properly

### ISSUE THREAD

**Issue by Seamonster778778778788** [Seamonster778778778788/SQBeyondPublic#528]
when I was testing with laser, he died and I invrestored him not meaning to kill him and I did the wrong date. 1/24/20 was the date I restored him, with armor. I did the wrong one, so I instead did the one from today. It didn't have the right gear, so I did the 1/24/20 one again and it was completely different items than the first time, with no armor or anything. Something with enchanted items is breaking it as they were all gone.

**Comment by GingerWalnut** [comment]
iirc, invrestore has two modes. One doesn't include inventories that have already been restored or inventories that have been claimed from insurance to prevent double dipping.

**Comment by Seamonster778778778788** [comment]
this has never been an issue before and I think you have to type true after the number that correlates with the death for that to apply

**Comment by Seamonster778778778788** [comment]
something to do with powertools i think
