### ISSUE TITLE
Capship claims disappearing

### ISSUE THREAD

**Issue by SirLoser** [Seamonster778778778788/SQBeyondPublic#537]
I play infrequently and somewhere between my logins my capship's claim will disappear. Sometimes the claim will stay for days, sometimes it'll be gone the very next. The capital ship itself is still registered, as it doesn't say I've registered a new ship upon clicking the sign, but the town claim is missing. Originally I thought it was a visual effect on dynmap but the ship's already been stolen once without the claim.

**Comment by HailOVERLORD** [comment]
This just happened to me again for the second day in a row. Something to do with server restart?
